on:
  - workflow_dispatch
name: Render PDF
jobs:
  render:
    runs-on: ubuntu-latest
    name: Render PDF
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -U pdfly

      - name: Render HTML files
        run: bundle exec ruby main.rb

      - name: Print HTML files to PDF files
        run: node print_to_pdf.js

      - name: Concatenate all PDF files into one
        run: pdfly cat rendered/*.pdf -o rendered/cards.pdf
